name: Hello World Workflow
run-name: Hello World Run
on:
  schedule:
    - cron: '*/3 * * * *'
jobs:
  First-Job:
    name: 1st-Job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Actor - ${{ github.actor }}"
      - run: echo "Event - ${{ github.event_name }}"
      - run: echo "Runner - ${{ runner.os }}"
      - name: Repo checkout
        uses: actions/checkout@v4
      - run: echo "Repo - ${{ github.repository }}"
      - run: echo "Branch - ${{ github.ref }}"
      - name: List files
        run: |
          ls ${{ github.workspace }}
      - run: echo "Job Status - ${{ job.status }}"
